package com.android.borutoapp.ui.theme

import androidx.compose.ui.unit.dp

val EXTRA_LARGE_PADDING = 40.dp
val LARGE_PADDING = 20.dp
val MEDIUM_PADDING = 16.dp
val SMALL_PADDING = 10.dp
val EXTRA_SMALL_PADDING = 6.dp

val PADDING_INDICATOR_WIDTH = 12.dp
val PADDING_INDICATOR_SPACING = 8.dp


val HERO_ITEM_HEIGHT = 400.dp
val NAME_PLACE_HOLDER_HEIGHT = 30.dp
val ABOUT_PLACE_HOLDER_HEIGHT = 20.dp
val RATING_PLACE_HOLDER_HEIGHT = 20.dp
val NETWORK_ERROR_ICON_SIZE = 120.dp
val TOP_APP_BAR_HEIGHT = 60.dp
val SMALL_BOTTOM_SHEET_HEIGHT = 140.dp

const val ABOUT_TEXT_MAX_LINES = 7